show=dmenu
normal_window=false
allow_images=true
hide_search=true
hide_scroll=true
# lines=4
# lines_additional_space=0
# blurred_background=true
# valign=Center
# dynamic_lines=true
width=150
height=185
prompt=Power menu

